[config]
fallback_color = '#8caaee'

[config.wallpaper]
arguments = [
  'img',
  '--transition-type',
  'grow',
  '--transition-pos',
  '0.894,0.960',
]
command = 'swww'
set = true

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/dotfiles/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.cava]
input_path = 'templates/cava-colors.ini'
output_path = '~/dotfiles/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.btop]
input_path = 'templates/btop-colors.theme'
output_path = '~/dotfiles/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop'

[templates.spotify]
input_path = 'templates/spicetify-colors.ini'
output_path = '~/dotfiles/.config/spicetify/Themes/Sleek/color.ini'
post_hook = 'spicetify refresh'

[templates.eww]
input_path = 'templates/eww-colors.scss'
output_path = '~/dotfiles/.config/eww/theme.scss'
post_hook = 'eww reload'

[templates.gtk3]
input_path = 'templates/gtk-colors.css'
output_path = '~/dotfiles/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = 'templates/gtk-colors.css'
output_path = '~/dotfiles/.config/gtk-4.0/gtk.css'

[templates.pywalfox]
input_path = 'templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.rofi]
input_path = 'templates/rofi-colors.rasi'
output_path = '~/dotfiles/.config/rofi/colors.rasi'

[templates.ghostty]
input_path = 'templates/ghostty-colors'
output_path = '~/dotfiles/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'
