[config]
fallback_color = "#8caaee"

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "grow", "--transition-pos", "0.894,0.960"]
set = true

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/dotfiles/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.cava]
input_path = 'templates/cava-colors.ini'
output_path = '~/dotfiles/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.btop]
input_path = 'templates/btop-colors.theme'
output_path = '~/dotfiles/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop'

[templates.spotify]
input_path = 'templates/spicetify-colors.ini'
output_path = '~/dotfiles/.config/spicetify/Themes/Sleek/color.ini'
post_hook = "spicetify refresh"

[templates.eww]
input_path = 'templates/eww-colors.scss'
output_path = '~/dotfiles/.config/eww/theme.scss'
post_hook = "eww reload"